// <auto-generated />
namespace LexiconLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednosatusondocumntmoduleenum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednosatusondocumntmoduleenum));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221155375_Added no satus on documnt module enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
